### ISSUE TITLE
Support jump hosts

### ISSUE THREAD

**Issue by johntdyer** [kohkimakimoto/essh#31]
Any plans to support jump hosts ? I am looking for something to replace https://github.com/moul/advanced-ssh-config

**Comment by kohkimakimoto** [comment]
@johntdyer Does it mean to use a gateway host?  Is it like the following connection?

```
[client PC] -- (ssh) -- [host A] -- (ssh) -- [host B]
```
If you mean the above functionality, Essh supports it as the below config:

```lua
--
-- network environment.
-- [your-computer] -- [getway-server] -- [web-server]
--

host "getway-server" {
    HostName = "192.168.0.1",
}

host "web-server" {
    HostName = "192.168.0.2",
    ProxyCommand = "ssh -q -F " .. essh.ssh_config .. " -W %h:%p getway-server",
}
```

You can connect `web-server` by the following:

```
$ essh web-server
```

see also: https://github.com/kohkimakimoto/essh/blob/master/docs/lua-vm.md#predefined-variables
