### ISSUE TITLE
Any plans to support defaults

### ISSUE THREAD

**Issue by johntdyer** [kohkimakimoto/essh#32]
Any plans to support default ssh options for all hosts ?

**Comment by kohkimakimoto** [comment]
Essh does not support default ssh options by its functionality. But you can achieve same thing by the Lua code. Try the below Lua code in the `~/.essh/config_override.lua`.

```lua
for i, h in pairs(find_hosts()) do
    if h.ServerAliveInterval == nil then
        h.ServerAliveInterval = "60"
    end
    if h.ForwardAgent == nil then
        h.ForwardAgent = "yes"
    end
end
```

`find_hosts` is a function to get all defined hosts.

`~/.essh/config_override.lua` is loaded after `~/.essh/config.lua`. So you can load all hosts defined  in the `~/.essh/config.lua`. see: https://github.com/kohkimakimoto/essh/blob/master/docs/configuration-files.md
