### ISSUE TITLE
Cannot execute task when password authentication is required

### ISSUE THREAD

**Issue by Dvineone** [kohkimakimoto/essh#64]
Cannot execute a task when password authentication is required. You suggest using a pipe to use stdin when using essh in #36 

So using echo | ./essh <taskname> will allow you to authenticate. <- Work around.

Is there anyway this can be resolved in code?

**Comment by kohkimakimoto** [comment]
Sorry, I don't know. As I always use essh with key authentication, it does not support password auth. But if you use **wrapper** task, you can use password for a task execution.

Example:
```lua
task "wrapper_task" {
    prepare = function(task)
        local question = require("question")
        local password = question.secret("Enter your password: ")
        task.props = {
            password = password
        }
    end,
    script = [=[
        echo $ESSH_TASK_PROPS_PASSWORD | essh main_task
    ]=]
}

task "main_task" {
    hidden = true,
    script = [=[
        # write your task...
    ]=]
}
```

The `wrapper_task` prompts you to input your password. And then, essh executes `main_task` with the inputted password.

**Comment by Dvineone** [comment]
Awesome. Thank you
