### ISSUE TITLE
Cannot Access Generated Config - (Windows)

### ISSUE THREAD

**Issue by Dvineone** [kohkimakimoto/essh#65]
When trying to access the generated config file using ssh command there is a permissions issue.

As you can see you can read the generated config file if you are using essh to print the config to the screen
![image](https://user-images.githubusercontent.com/4534564/78581402-744d3380-77f9-11ea-9cb6-e32ed4c9963e.png)

But when trying to connect to the host the ssh client cannot read the config file
![image](https://user-images.githubusercontent.com/4534564/78581766-ecb3f480-77f9-11ea-926c-1486aa04ea20.png)

**Comment by kohkimakimoto** [comment]
Unfortunately I don't have windows environment. I can't inspect the issue. If you can solve the issue, please send a PR .

**Comment by Dvineone** [comment]
I have the issue resolved but i cannot create a branch to create a pull request.

**Comment by kohkimakimoto** [comment]
Thanks for your PR https://github.com/kohkimakimoto/essh/pull/66
I merged it and released new version and binaries.
https://github.com/kohkimakimoto/essh/releases/tag/v3.4.0

**Comment by kohkimakimoto** [comment]
I think this issue was solved by #66
